services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock-server
    volumes:
      - ./games/minecraft/data:/data
      - ./games/minecraft/data/worlds:/data/worlds
      - ./shared/logs:/var/log/minecraft
    ports:
      - "19132:19132/udp"  # IPv4 gameplay
      - "19133:19133/udp"  # IPv6 gameplay
    environment:
      - EULA=TRUE
      - GAMEMODE=survival
      - DIFFICULTY=normal
      - LEVEL_NAME=${MINECRAFT_LEVEL_NAME:-Bedrock level}
      - ALLOW_CHEATS=false
      - MAX_PLAYERS=10
      - ONLINE_MODE=true
      - WHITE_LIST=false
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 4G
    restart: unless-stopped
  rust:
    image: didstopia/rust-server
    ports:
      - 28015-28016:28015-28016
      - 28015:28015/udp
      - 8080:8080
    volumes:
      - rustds-data:/steamcmd/rust
      - ./games/rust/logs:/steamcmd/rust/logs
    environment:
      TZ: Asia/Tokyo
      RUST_SERVER_STARTUP_ARGUMENTS: -batchmode -nographics  +decay.scale 0.3
      RUST_SERVER_IDENTITY: ${RUST_SERVER_IDENTITY:-rust}
      RUST_SERVER_SEED: ${RUST_SERVER_SEED:-1234568}
      RUST_SERVER_NAME: ${RUST_SERVER_NAME:-Rust dedicated server}
      RUST_SERVER_DESCRIPTION: ${RUST_SERVER_DESCRIPTION:-A playroom for PlusUltra members.}
      RUST_SERVER_URL: ${RUST_SERVER_URL:-https://xxx.xxx.xxx/}
      RUST_SERVER_BANNER_URL: ${RUST_SERVER_BANNER_URL:-http://xxx.xxx.xxx/banner.jpg}
      RUST_RCON_PASSWORD: ${RUST_RCON_PASSWORD:-xxxxxxxxxxxxxxxx}
      RUST_UPDATE_CHECKING: ${RUST_UPDATE_CHECKING:-1}
      RUST_SERVER_WORLDSIZE: ${RUST_SERVER_WORLDSIZE:-3500}
      RUST_SERVER_MAXPLAYERS: ${RUST_SERVER_MAXPLAYERS:-15}
      RUST_SERVER_SAVE_INTERVAL: ${RUST_SERVER_SAVE_INTERVAL:-300}
      RUST_OXIDE_ENABLED: 1
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 64G
        reservations:
          cpus: '2'
          memory: 8G
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1

volumes:
  rustds-data: