services:
  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock-server
    volumes:
      - ./games/minecraft/data:/data
      - ./games/minecraft/data/worlds:/data/worlds
      - ./shared/logs:/var/log/minecraft
    ports:
      - "19132:19132/udp"  # IPv4 gameplay
      - "19133:19133/udp"  # IPv6 gameplay
    environment:
      - EULA=TRUE
      - GAMEMODE=survival
      - DIFFICULTY=normal
      - LEVEL_NAME=${MINECRAFT_LEVEL_NAME:-Bedrock level}
      - ALLOW_CHEATS=false
      - MAX_PLAYERS=10
      - ONLINE_MODE=true
      - WHITE_LIST=false
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 4G
    restart: unless-stopped
  rust:
    image: didstopia/rust-server
    container_name: rust-server
    ports:
      - 28015-28016:28015-28016
      - 28015:28015/udp
      - 8080:8080
    volumes:
      - rustds-data:/steamcmd/rust
      - ./games/rust/logs:/steamcmd/rust/logs
    environment:
      TZ: Asia/Tokyo
      RUST_SERVER_STARTUP_ARGUMENTS: -batchmode -nographics  +decay.scale 0.3
      RUST_SERVER_IDENTITY: ${RUST_SERVER_IDENTITY:-rust}
      RUST_SERVER_SEED: ${RUST_SERVER_SEED:-1234568}
      RUST_SERVER_NAME: ${RUST_SERVER_NAME:-Rust dedicated server}
      RUST_SERVER_DESCRIPTION: ${RUST_SERVER_DESCRIPTION:-A playroom for PlusUltra members.}
      RUST_SERVER_URL: ${RUST_SERVER_URL:-https://xxx.xxx.xxx/}
      RUST_SERVER_BANNER_URL: ${RUST_SERVER_BANNER_URL:-http://xxx.xxx.xxx/banner.jpg}
      RUST_RCON_PASSWORD: ${RUST_RCON_PASSWORD:-xxxxxxxxxxxxxxxx}
      RUST_UPDATE_CHECKING: ${RUST_UPDATE_CHECKING:-1}
      RUST_SERVER_WORLDSIZE: ${RUST_SERVER_WORLDSIZE:-3500}
      RUST_SERVER_MAXPLAYERS: ${RUST_SERVER_MAXPLAYERS:-15}
      RUST_SERVER_SAVE_INTERVAL: ${RUST_SERVER_SAVE_INTERVAL:-300}
      RUST_OXIDE_ENABLED: 1
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 64G
        reservations:
          cpus: '2'
          memory: 8G
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1

  ark-island:
    build: .
    image: acekorneya/asa_server:latest
    container_name: ark-island
    restart: unless-stopped
    environment:
      - PUID=1001                            # The UID to run server as
      - PGID=1001                            # The GID to run server as
      - BATTLEEYE=FALSE                      # Set to TRUE to use BattleEye, FALSE to not use BattleEye
      - RCON_ENABLED=TRUE                    # Needed for Graceful Shutdown / Updates / Server Notifications
      - DISPLAY_POK_MONITOR_MESSAGE=FALSE    # TRUE to Show the Server Monitor Messages / Update Monitor 
      - UPDATE_SERVER=TRUE                   # Enable or disable update checks
      - CHECK_FOR_UPDATE_INTERVAL=24         # Check for Updates interval in hours
      - UPDATE_WINDOW_MINIMUM_TIME=12:00 AM  # Defines the minimum time, relative to server time, when an update check should run
      - UPDATE_WINDOW_MAXIMUM_TIME=11:59 PM  # Defines the maximum time, relative to server time, when an update check should run
      - RESTART_NOTICE_MINUTES=30            # Duration in minutes for notifying players before a server restart due to updates
      - ENABLE_MOTD=FALSE                    # Enable or disable Message of the Day
      - MOTD=                                # Message of the Day
      - MOTD_DURATION=30                     # Duration for the Message of the Day
      - MAP_NAME=TheIsland
      - SESSION_NAME=${ARK_ISLAND_SESSION_NAME:-ark-island}
      - SERVER_ADMIN_PASSWORD=${ARK_SERVER_ADMIN_PASSOWRD:-adminpassword}
      - SERVER_PASSWORD=${ARK_SERVER_PASSWORD:-password}         # Set a server password or leave it blank (ONLY NUMBERS AND CHARACTERS ARE ALLOWED BY DEVS)
      - ASA_PORT=7777
      - RCON_PORT=27020
      - MAX_PLAYERS=19
      - CLUSTER_ID=cluster
      - MOD_IDS=933975,929868,935528         # Add your mod IDs here, separated by commas, e.g., 123456789,987654321
      - CUSTOM_SERVER_ARGS=                  # If You need to add more Custom Args -ForceRespawnDinos -ForceAllowCaveFlyers
    ports:
      - "7777:7777/tcp"
      - "7777:7777/udp"
    volumes:
      - "./games/ark/ASA_Island:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "./games/ark/Dedicated Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "./games/ark/Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
    mem_limit: 32G 
  ark-scorched:
    build: .
    image: acekorneya/asa_server:latest
    container_name: ark-scorched
    restart: unless-stopped
    environment:
      - PUID=1001                            # The UID to run server as
      - PGID=1001                            # The GID to run server as
      - BATTLEEYE=FALSE                      # Set to TRUE to use BattleEye, FALSE to not use BattleEye
      - RCON_ENABLED=TRUE                    # Needed for Graceful Shutdown / Updates / Server Notifications
      - DISPLAY_POK_MONITOR_MESSAGE=FALSE    # TRUE to Show the Server Monitor Messages / Update Monitor 
      - UPDATE_SERVER=TRUE                   # Enable or disable update checks
      - CHECK_FOR_UPDATE_INTERVAL=24         # Check for Updates interval in hours
      - UPDATE_WINDOW_MINIMUM_TIME=12:00 AM  # Defines the minimum time, relative to server time, when an update check should run
      - UPDATE_WINDOW_MAXIMUM_TIME=11:59 PM  # Defines the maximum time, relative to server time, when an update check should run
      - RESTART_NOTICE_MINUTES=30            # Duration in minutes for notifying players before a server restart due to updates
      - ENABLE_MOTD=FALSE                    # Enable or disable Message of the Day
      - MOTD=                                # Message of the Day
      - MOTD_DURATION=30                     # Duration for the Message of the Day
      - MAP_NAME=ScorchedEarth
      - SESSION_NAME=${ARK_SCORCHED_SESSION_NAME:-ark-scorched}
      - SERVER_ADMIN_PASSWORD=${ARK_SERVER_ADMIN_PASSOWRD:-adminpassword}
      - SERVER_PASSWORD=${ARK_SERVER_PASSWORD:-password}         # Set a server password or leave it blank (ONLY NUMBERS AND CHARACTERS ARE ALLOWED BY DEVS)
      - ASA_PORT=7778
      - RCON_PORT=27021
      - MAX_PLAYERS=19
      - CLUSTER_ID=cluster
      - MOD_IDS=933975,929868,935528         # Add your mod IDs here, separated by commas, e.g., 123456789,987654321
      - CUSTOM_SERVER_ARGS=                  # If You need to add more Custom Args -ForceRespawnDinos -ForceAllowCaveFlyers
    ports:
      - "7778:7778/tcp"
      - "7778:7778/udp"
    volumes:
      - "./games/ark/scorchedEarth/ASA_scorchedEarth:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame"
      - "./games/ark/scorchedEarth/Dedicated_Server:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server"
      - "./games/ark/Cluster:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ShooterGame"
      - "./games/ark/config/Game.ini:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame/Saved/Config/WindowsServer/Game.ini"
      - "./games/ark/config/GameUserSettings.ini:/usr/games/.wine/drive_c/POK/Steam/steamapps/common/ARK Survival Ascended Dedicated Server/ShooterGame/Saved/Config/WindowsServer/GameUserSettings.ini"
    mem_limit: 32G 

volumes:
  rustds-data:
