services:
  game-server-base:
    build:
      context: ./games/base
      dockerfile: Dockerfile
    image: game-server-base:latest

  minecraft:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock-server
    volumes:
      - ./games/minecraft/data:/data
      - ./games/minecraft/data/worlds:/data/worlds
      - ./shared/logs:/var/log/minecraft
    ports:
      - "19132:19132/udp"  # IPv4 gameplay
      - "19133:19133/udp"  # IPv6 gameplay
    environment:
      - EULA=TRUE
      - GAMEMODE=survival
      - DIFFICULTY=normal
      - LEVEL_NAME=${MINECRAFT_LEVEL_NAME:-Bedrock level}
      - ALLOW_CHEATS=false
      - MAX_PLAYERS=10
      - ONLINE_MODE=true
      - WHITE_LIST=false
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 16G
        reservations:
          cpus: '2'
          memory: 4G
    restart: unless-stopped
  rust:
    build:
      context: ./games/rust
      dockerfile: Dockerfile
    container_name: rust-server
    ports:
      - "28015:28015/udp"  # ゲームポート
      - "28016:28016/udp"  # RCONポート
      - "28017:28017/udp"  # アプリケーションポート
    volumes:
      - ./games/rust/data:/steamcmd/games/Rust
      - ./games/rust/scripts/start.sh:/steamcmd/games/start.sh
      - ./games/rust/backup:/backup
    environment:
      - SERVER_NAME=${RUST_SERVER_NAME}
      - SERVER_DESCRIPTION=${RUST_SERVER_DESCRIPTION}
      - MAX_PLAYERS=${RUST_MAX_PLAYERS}
      - SEED=${RUST_SEED}
      - WORLD_SIZE=${RUST_WORLD_SIZE}
      - SAVE_INTERVAL=${RUST_SAVE_INTERVAL}
      - LANG=ja_JP.UTF-8
      - LANGUAGE=ja_JP:ja
      - LC_ALL=ja_JP.UTF-8
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    restart: unless-stopped
    depends_on:
      - game-server-base
